import sys

# collect_ignore = [] # to list whole files to be ignored


# QuixBugs test cases from the "correct" folder that are broken out of the box
QUIX_FAILING_OUT_OF_THE_BOX = [
    "benchmark/quixbugs/test_quix.py::TestQuix::test_quix_170_knapsack_9", # timeout, unperformant implementation with big input
    "benchmark/quixbugs/test_quix.py::TestQuix::test_quix_229_levenshtein_3", # timeout, unperformant implementation with big input
    "benchmark/quixbugs/test_quix.py::TestQuix::test_quix_086_sqrt_4", # float comparison
    "benchmark/quixbugs/test_quix.py::TestQuix::test_quix_087_sqrt_5", # float comparison
]

# issues that could be fixed by implementing relevant slicing.
RELEVANT_SLICING_ISSUES = [
    "benchmark/quixbugs/test_quix_failures.py::TestQuixFailure::test_quix8",
    "benchmark/refactory/test_new_refactory_failures.py::TestNewRefactoryFailures::test_timeout_1",
    "benchmark/refactory/test_new_refactory_failures.py::TestNewRefactoryFailures::test_timeout_2",
    "benchmark/refactory/test_new_refactory_failures.py::TestNewRefactoryFailures::test_timeout_3",
    "benchmark/refactory/test_new_refactory_failures.py::TestNewRefactoryFailures::test_timeout_5",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_028_hanoi_1",
]

# our slicer is built on the assumption that functions are called by value, therefore functions that build on
# call by reference produce broken slices.
CALL_BY_REFERENCE_ISSUES = [
    "slicing/test_evaluation_different_results.py::TestEvaluationDifferentResult::test_dependecy_issue_importance_to_drop_some_items",
    "slicing/test_evaluation_different_results.py::TestEvaluationDifferentResult::test_parameter_by_reference_modified_inside_function",
    "slicing/test_evaluation_different_results.py::TestEvaluationDifferentResult::test_parameter_by_reference_modified_inside_function_1",
    "slicing/test_evaluation_different_results.py::TestEvaluationDifferentResult::test_parameter_by_reference_modified_inside_function_2",
    "slicing/test_evaluation_different_results.py::TestEvaluationDifferentResult::test_parameter_by_reference_modified_inside_function_minimized",
]

# performance heavy tests that need readjusting of the timeouts to succeed
RECURSION_PERFORMANCE_ISSUES = [
    "slicing/test_slicing_recursion_error.py::TestSlicingRecursionError::test_recursion_error_10",
    "slicing/test_slicing_recursion_error.py::TestSlicingRecursionError::test_recursion_error_4",
    "slicing/test_slicing_recursion_error.py::TestSlicingRecursionError::test_recursion_error_5",
    "slicing/test_slicing_recursion_error.py::TestSlicingRecursionError::test_recursion_error_9",
]

# tests failing due to "unsupported" slicing exception
# see ast_tree_tracer/transformer_utils.py::check_for_unsupported_constructs for a complete list
# of unsupported constructs and keywords
NOT_SUPPORTED_CONSTRUCTS = [
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_143_rpn_eval_0",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_144_rpn_eval_1",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_145_rpn_eval_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_146_rpn_eval_3",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_147_rpn_eval_4",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_148_rpn_eval_5",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_219_flatten_0",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_220_flatten_1",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_221_flatten_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_222_flatten_3",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_223_flatten_4",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_224_flatten_5",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_225_flatten_6",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_157_kheapsort_0",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_158_kheapsort_1",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_159_kheapsort_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_160_kheapsort_3",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1023_correct_1_694_py0",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1024_correct_1_694_py1",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1025_correct_1_694_py2",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1026_correct_1_694_py3",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1027_correct_1_694_py4",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1028_correct_1_694_py5",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1029_correct_1_694_py6",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1030_correct_1_694_py7",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1031_correct_1_694_py8",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1032_correct_1_694_py9",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1033_correct_1_694_py10",


]

# Tests that fail either due to excessive runtime or above described slicing issue that could be resolved with relevant slicing
TIMEOUTS_QUIX_REFACTORY = [
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_108_longest_common_subsequence_0",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_109_longest_common_subsequence_1",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_111_longest_common_subsequence_3",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_117_longest_common_subsequence_9",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_163_knapsack_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_170_knapsack_9",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_226_levenshtein_0",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_228_levenshtein_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_229_levenshtein_3",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_230_levenshtein_4",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_002_possible_change_2",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_005_possible_change_5",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_006_possible_change_6",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_007_possible_change_7",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_008_possible_change_8",
    "benchmark/quixbugs/test_quix_dyn_slicing.py::TestDynSliceQuix::test_dyn_quix_009_possible_change_9",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3665_correct_1_458_py2",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3666_correct_1_458_py3",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3667_correct_1_458_py4",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3669_correct_1_458_py6",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3671_correct_1_458_py8",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3859_correct_1_526_py2",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_2819_correct_1_526_py3",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_2820_correct_1_526_py4",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_2822_correct_1_526_py6",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_2824_correct_1_526_py8",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1967_correct_1_219_py9",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_1968_correct_1_219_py10",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_5608_correct_1_088_py9",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_5609_correct_1_088_py10",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3859_correct_1_085_py9",
    "benchmark/refactory/test_refactory.py::TestRefactory::test_dyn_refactory_3860_correct_1_085_py10",
]

METAMORPHIC_TIMEOUT = [
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_002_possible_change_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_005_possible_change_5",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_006_possible_change_6",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_007_possible_change_7",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_008_possible_change_8",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_009_possible_change_9",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_108_longest_common_subsequence_0",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_109_longest_common_subsequence_1",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_111_longest_common_subsequence_3",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_117_longest_common_subsequence_9",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_163_knapsack_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_170_knapsack_9",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_226_levenshtein_0",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_227_levenshtein_1",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_228_levenshtein_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_229_levenshtein_3",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_230_levenshtein_4",

]

METAMORPHIC_UNSUPPORTED = [
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_143_rpn_eval_0",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_144_rpn_eval_1",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_145_rpn_eval_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_146_rpn_eval_3",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_147_rpn_eval_4",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_148_rpn_eval_5",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_157_kheapsort_0",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_158_kheapsort_1",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_159_kheapsort_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_160_kheapsort_3",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_219_flatten_0",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_220_flatten_1",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_221_flatten_2",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_222_flatten_3",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_223_flatten_4",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_224_flatten_5",
    "metamorphic_testing/test_quix_slice_len_check.py::TestQuixSliceLen::test_quix_slice_len_225_flatten_6",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1023_correct_1_694_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1024_correct_1_694_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1025_correct_1_694_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1026_correct_1_694_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1027_correct_1_694_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1028_correct_1_694_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1029_correct_1_694_py6",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1030_correct_1_694_py7",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1031_correct_1_694_py8",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1032_correct_1_694_py9",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_1033_correct_1_694_py10",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4365_correct_3_197_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4366_correct_3_197_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4367_correct_3_197_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4368_correct_3_197_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4633_correct_3_425_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4634_correct_3_425_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4635_correct_3_425_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4636_correct_3_425_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4793_correct_3_043_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4794_correct_3_043_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4795_correct_3_043_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4796_correct_3_043_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4983_correct_4_020_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4984_correct_4_020_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4985_correct_4_020_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4986_correct_4_020_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4987_correct_4_020_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_4988_correct_4_020_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5043_correct_4_154_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5044_correct_4_154_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5045_correct_4_154_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5046_correct_4_154_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5047_correct_4_154_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5048_correct_4_154_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5295_correct_4_410_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5296_correct_4_410_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5297_correct_4_410_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5298_correct_4_410_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5299_correct_4_410_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5300_correct_4_410_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5367_correct_4_001_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5368_correct_4_001_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5369_correct_4_001_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5370_correct_4_001_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5371_correct_4_001_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5372_correct_4_001_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5451_correct_4_279_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5452_correct_4_279_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5453_correct_4_279_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5454_correct_4_279_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5455_correct_4_279_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5456_correct_4_279_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5631_correct_4_241_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5632_correct_4_241_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5633_correct_4_241_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5634_correct_4_241_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5635_correct_4_241_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5636_correct_4_241_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5691_correct_4_220_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5692_correct_4_220_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5693_correct_4_220_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5694_correct_4_220_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5695_correct_4_220_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5696_correct_4_220_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5757_correct_4_012_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5758_correct_4_012_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5759_correct_4_012_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5760_correct_4_012_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5761_correct_4_012_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5762_correct_4_012_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5769_correct_4_209_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5770_correct_4_209_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5771_correct_4_209_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5772_correct_4_209_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5773_correct_4_209_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5774_correct_4_209_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5973_correct_4_245_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5974_correct_4_245_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5975_correct_4_245_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5976_correct_4_245_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5977_correct_4_245_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_5978_correct_4_245_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6093_correct_4_170_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6094_correct_4_170_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6095_correct_4_170_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6096_correct_4_170_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6097_correct_4_170_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6098_correct_4_170_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6177_correct_4_076_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6178_correct_4_076_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6179_correct_4_076_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6180_correct_4_076_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6181_correct_4_076_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6182_correct_4_076_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6225_correct_4_039_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6226_correct_4_039_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6227_correct_4_039_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6228_correct_4_039_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6229_correct_4_039_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6230_correct_4_039_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6519_correct_5_095_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6520_correct_5_095_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6521_correct_5_095_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6522_correct_5_095_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6523_correct_5_095_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6524_correct_5_095_py5",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6829_correct_5_029_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6830_correct_5_029_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6831_correct_5_029_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6832_correct_5_029_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_6833_correct_5_029_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7074_correct_5_157_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7075_correct_5_157_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7076_correct_5_157_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7077_correct_5_157_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7078_correct_5_157_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7414_correct_5_239_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7415_correct_5_239_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7416_correct_5_239_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7417_correct_5_239_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7418_correct_5_239_py4",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7559_correct_5_175_py0",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7560_correct_5_175_py1",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7561_correct_5_175_py2",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7562_correct_5_175_py3",
    "metamorphic_testing/test_refactory_slice_len_check.py::TestRefactorySliceLen::test_refactory_slice_len_7563_correct_5_175_py4",
]

def pytest_configure(config):
    config.option.deselect = QUIX_FAILING_OUT_OF_THE_BOX +\
                             RELEVANT_SLICING_ISSUES +\
                             CALL_BY_REFERENCE_ISSUES +\
                             RECURSION_PERFORMANCE_ISSUES + \
                             NOT_SUPPORTED_CONSTRUCTS +\
                             TIMEOUTS_QUIX_REFACTORY  + \
                             METAMORPHIC_UNSUPPORTED + \
                             METAMORPHIC_TIMEOUT
